{"uuid": "c0171b00-9a2f-43a5-8ca2-87aabfa38ecd", "children": ["09d004b7-a174-48ef-bd88-038926b7cfee"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource\n\n", "trace": "  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\base_test.py\", line 27, in setup_method\n    self.driver = webdriver.Remote(\n                  ~~~~~~~~~~~~~~~~^\n        command_executor=self.config.get_appium_server_url(),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options\n        ^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 238, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 329, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748428243480, "stop": 1748428245533}], "start": 1748428243480, "stop": 1748428245617}