{"uuid": "f9f81b0c-b580-447a-82b3-c619f833455f", "children": ["6fdfdc18-c356-4c65-a293-d057ba7946ff"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20000ms\n    at getResponseForW3CError (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1143:9)\n    at asyncHandler (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:487:57)\n", "trace": "  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\base_test.py\", line 38, in setup_method\n    self.driver = webdriver.Remote(\n                  ~~~~~~~~~~~~~~~~^\n        command_executor=self.config.get_appium_server_url(),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options\n        ^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 238, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 329, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748511035364, "stop": 1748511057568}], "start": 1748511035364, "stop": 1748511057867}