{"name": "使用无效凭据登录", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'NoneType' is not iterable", "trace": "self = <flutter_app_test.testcases.test_login.TestLogin object at 0x000001CB2C122990>\n\n    @allure.story(\"异常登录\")\n    @allure.title(\"使用无效凭据登录\")\n    def test_invalid_login(self):\n        \"\"\"测试使用无效的用户名和密码登录\"\"\"\n        login_page = LoginPage(self.driver)\n    \n        with allure.step(\"输入无效的用户名和密码\"):\n            login_page.login(\"invalid_user\", \"invalid_password\")\n    \n        with allure.step(\"验证错误信息显示\"):\n            error_message = login_page.get_error_message()\n>           assert \"Invalid credentials\" in error_message\nE           TypeError: argument of type 'NoneType' is not iterable\n\ntestcases\\test_login.py:24: TypeError"}, "description": "测试使用无效的用户名和密码登录", "steps": [{"name": "输入无效的用户名和密码", "status": "passed", "start": 1748517620856, "stop": 1748517629468}, {"name": "验证错误信息显示", "status": "broken", "statusDetails": {"message": "TypeError: argument of type 'NoneType' is not iterable\n", "trace": "  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\test_login.py\", line 24, in test_invalid_login\n    assert \"Invalid credentials\" in error_message\n"}, "start": 1748517629468, "stop": 1748517640061}], "start": 1748517620856, "stop": 1748517640062, "uuid": "c34ccba6-c3a9-46cf-a732-f0bf7087d0a7", "historyId": "f85285519da8525fb5620425bca75abe", "testCaseId": "f85285519da8525fb5620425bca75abe", "fullName": "testcases.test_login.TestLogin#test_invalid_login", "labels": [{"name": "story", "value": "异常登录"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-QVK4EQ1"}, {"name": "thread", "value": "5280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}