{"uuid": "cad37f44-06d1-4de2-8a5a-ce63585edf18", "children": ["d05af6f4-8730-4c06-80dc-4b8f473061e6"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "failed", "statusDetails": {"message": "Failed: Failed to initialize driver: Message: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Neither ANDROID_HOME nor ANDROID_SDK_ROOT environment variable was exported. Read https://developer.android.com/studio/command-line/variables for more details\n    at getResponseForW3CError (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1143:9)\n    at asyncHandler (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:487:57)\n", "trace": "  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\test_login.py\", line 39, in setup_method\n    pytest.fail(f\"Failed to initialize driver: {str(e)}\")\n    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 198, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1748434286325, "stop": 1748434286467}], "start": 1748434286325, "stop": 1748434286572}