{"uuid": "ed64bd5f-8cd4-4c10-bbdd-72bdc9057ac0", "children": ["c29f1f37-ae9b-4104-a43d-db3f08cda0f5"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\lv\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 196eea2b install -g 'C:\\\\Program Files\\\\Appium Server GUI\\\\resources\\\\app\\\\node_modules\\\\appium\\\\node_modules\\\\io.appium.settings\\\\apks\\\\settings_apk-debug.apk'' exited with code 1'; Command output: adb: failed to install C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk: \r\nException occurred while executing 'install':\r\njava.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag\r\n\tat com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:798)\r\n\tat com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:617)\r\n\tat com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\lv\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s 196eea2b install -g 'C:\\\\Program Files\\\\Appium Server GUI\\\\resources\\\\app\\\\node_modules\\\\appium\\\\node_modules\\\\io.appium.settings\\\\apks\\\\settings_apk-debug.apk'' exited with code 1'; Command output: adb: failed to install C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk: \r\nException occurred while executing 'install':\r\njava.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag\r\n\tat com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:798)\r\n\tat com.android.server.pm.PackageInstallerService.createSession(PackageInstallerService.java:617)\r\n\tat com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellC\n    at getResponseForW3CError (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\errors.js:804:9)\n    at asyncHandler (C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\appium-base-driver\\lib\\protocol\\protocol.js:380:37)\n", "trace": "  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\base_test.py\", line 38, in setup_method\n    self.driver = webdriver.Remote(\n                  ~~~~~~~~~~~~~~~~^\n        command_executor=self.config.get_appium_server_url(),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options\n        ^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 238, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 329, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748485652734, "stop": 1748485656918}], "start": 1748485652734, "stop": 1748485656940}