{"name": "使用无效凭据登录", "status": "failed", "statusDetails": {"message": "AssertionError: 未检测到错误弹窗\nassert None is not None", "trace": "self = <flutter_app_test.testcases.test_login.TestLogin object at 0x000001B64C9FE990>\n\n    @allure.story(\"异常登录\")\n    @allure.title(\"使用无效凭据登录\")\n    def test_invalid_login(self):\n        \"\"\"测试使用无效的用户名和密码登录\"\"\"\n        login_page = LoginPage(self.driver)\n    \n        with allure.step(\"输入无效的用户名和密码\"):\n            login_page.login(\"invalid_user\", \"invalid_password\")\n    \n        with allure.step(\"验证错误信息显示\"):\n            error_message = login_page.get_error_message()\n>           assert error_message is not None, \"未检测到错误弹窗\"\nE           AssertionError: 未检测到错误弹窗\nE           assert None is not None\n\ntestcases\\test_login.py:24: AssertionError"}, "description": "测试使用无效的用户名和密码登录", "steps": [{"name": "输入无效的用户名和密码", "status": "passed", "start": 1748520146694, "stop": 1748520153795}, {"name": "验证错误信息显示", "status": "failed", "statusDetails": {"message": "AssertionError: 未检测到错误弹窗\nassert None is not None\n", "trace": "  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\test_login.py\", line 24, in test_invalid_login\n    assert error_message is not None, \"未检测到错误弹窗\"\n"}, "start": 1748520153795, "stop": 1748520164910}], "start": 1748520146694, "stop": 1748520164910, "uuid": "43a003ab-2ab4-47da-a1b5-ff6ace3a710d", "historyId": "f85285519da8525fb5620425bca75abe", "testCaseId": "f85285519da8525fb5620425bca75abe", "fullName": "testcases.test_login.TestLogin#test_invalid_login", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "异常登录"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-QVK4EQ1"}, {"name": "thread", "value": "27056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}