{"uuid": "1b711151-55d7-48cb-a9a2-3106bb0906dd", "children": ["d79c158a-5960-4fac-bef3-41cd3885738b"], "befores": [{"name": "_xunit_setup_method_fixture_TestLogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.newpay.merchant' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\lv\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s emulator-5554 shell am start-activity -W -n com.newpay.merchant/com.newpay.merchant.ui.activity.StartActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.newpay.merchant/.ui.activity.StartActivity }\r\nError type 3\r\nError: Activity class {com.newpay.merchant/com.newpay.merchant.ui.activity.StartActivity} does not exist.\r\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Cannot start the 'com.newpay.merchant' application. Consider checking the driver's troubleshooting documentation. Original error: Error executing adbExec. Original error: 'Command 'C:\\\\Users\\\\lv\\\\AppData\\\\Local\\\\Android\\\\Sdk\\\\platform-tools\\\\adb.exe -P 5037 -s emulator-5554 shell am start-activity -W -n com.newpay.merchant/com.newpay.merchant.ui.activity.StartActivity -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -f 0x10200000' exited with code 1'; Command output: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.newpay.merchant/.ui.activity.StartActivity }\r\nError type 3\r\nError: Activity class {com.newpay.merchant/com.newpay.merchant.ui.activity.StartActivity} does not exist.\r\n\n    at getResponseForW3CError (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.js:1143:9)\n    at asyncHandler (C:\\Users\\lv\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.js:487:57)\n", "trace": "  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 899, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\_pytest\\python.py\", line 777, in _call_with_optional_argument\n    func(arg)\n    ~~~~^^^^^\n  File \"C:\\项目文件\\localAll\\flutter_app_test\\testcases\\base_test.py\", line 38, in setup_method\n    self.driver = webdriver.Remote(\n                  ~~~~~~~~~~~~~~~~^\n        command_executor=self.config.get_appium_server_url(),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options\n        ^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 238, in __init__\n    super().__init__(\n    ~~~~~~~~~~~~~~~~^\n        command_executor=command_executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<3 lines>...\n        client_config=client_config,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 329, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"c:\\项目文件\\localAll\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1748504094196, "stop": 1748504106252}], "start": 1748504094196, "stop": 1748504106415}